r"""Emit ``values.tex``: every CSV cell of the frozen tables as a LaTeX macro.

The manuscript never types a result number by hand.  Prose numbers are
``\val{<key>}`` where key = ``<table>:<row-key>:<column>`` and the table name
drops the ``tab-`` prefix, e.g. ``\val{scalability:mu_msgs:3b-rf1}`` or
``\val{e4r-mu:1b-rf1:mu_msgs}``.  Row keys join the table's key columns with
``/`` (``\val{e2-summary:3b-rf1/75:err_ack_rel_med}``).

LaTeX side (preamble)::

    \makeatletter
    \newcommand{\val}[1]{\ifcsname val@#1\endcsname
        \csname val@#1\endcsname\else\textcolor{red}{[brak: #1]}\fi}
    \makeatother
    \IfFileExists{tables/values.tex}{\input{tables/values.tex}}{}

Numbers are emitted raw (``.`` decimal point) so the manuscript can format
them with siunitx (``\num{\val{...}}`` -> Polish decimal comma, thin-space
thousands).  Empty cells produce no macro, so ``\val`` shows the red
placeholder -- a missing value is always visible, never silently blank.

Also writes ``values-index.md`` (all keys) next to the tex file.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

KEY_COLUMNS = {
    "rate-correction": ["config", "rho_target"],
    "e1-tau": ["config", "run"],
    "e2-summary": ["config", "rho_target"],
    "e2bp-summary": ["config", "rho_target", "variant"],
    "e2bp-ladder": ["config", "rho_target", "variant", "run"],
    "e4-ladder": ["config", "P", "run"],
    "e4r-ladder": ["config", "rate", "run"],
    "calibration": ["config", "parameter"],
    "run-census": ["exp", "config", "label"],
    "time-budget": ["exp", "config"],
    "partition-usage": ["topic", "partition", "broker"],
    "partition-imbalance": ["topic"],
    "v1-e2-ladder": ["rung", "run"],
    "v1-e2-summary": ["rung"],
    "v1-e1": ["run"],
    "v1-e4": ["run", "producer"],
    "e2-error-v1-v2": ["source", "rho_target"],
    "omb-evidence": ["config", "rung", "run"],
    "omb-profile": ["config"],
    "mu-summary": ["config"],
    "scalability-err": ["quantity"],
    "kingman-error": ["config"],
}
PREFIX_KEY_COLUMNS = {
    "e2-ladder-": ["rho_target", "run"],
    "e4-attempts-": ["label", "run"],
}


def _key_columns(table: str, header: list[str]) -> list[str]:
    if table in KEY_COLUMNS:
        return [c for c in KEY_COLUMNS[table] if c in header] or header[:1]
    for prefix, cols in PREFIX_KEY_COLUMNS.items():
        if table.startswith(prefix):
            return [c for c in cols if c in header] or header[:1]
    return header[:1]


def _tex_safe(s: str) -> str:
    return (s.replace("\\", "/").replace("{", "(").replace("}", ")")
             .replace("%", r"\%").replace("#", r"\#").replace("&", r"\&")
             .replace("_", r"\_").replace("^", r"\^{}"))


def collect(out_tables: Path) -> dict[str, str]:
    """{key: raw cell string} for every non-empty cell of every tab-*.csv."""
    values: dict[str, str] = {}
    for csv_path in sorted(Path(out_tables).glob("tab-*.csv")):
        table = csv_path.stem[len("tab-"):]
        with csv_path.open(encoding="utf-8", newline="") as fh:
            reader = csv.reader(fh)
            try:
                header = next(reader)
            except StopIteration:
                continue
            key_cols = _key_columns(table, header)
            idx = {c: i for i, c in enumerate(header)}
            for row in reader:
                if not row or len(row) != len(header):
                    continue
                row_key = "/".join(row[idx[c]] for c in key_cols)
                for col, cell in zip(header, row):
                    if col in key_cols or cell == "":
                        continue
                    values[f"{table}:{row_key}:{col}"] = cell
    return values


def write_values_tex(out_tables: Path) -> int:
    out_tables = Path(out_tables)
    values = collect(out_tables)
    lines = ["% Generated by analysis/values_tex.py -- DO NOT EDIT (every number comes from tab-*.csv)"]
    for key in sorted(values):
        val = values[key]
        try:
            float(val)
            body = val
        except ValueError:
            body = _tex_safe(val)
        lines.append(f"\\expandafter\\def\\csname val@{key}\\endcsname{{{body}}}")
    (out_tables / "values.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    index = ["# values.tex index", "", f"{len(values)} keys", ""]
    index += [f"- `{k}` = `{values[k]}`" for k in sorted(values)]
    (out_tables / "values-index.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    return len(values)


if __name__ == "__main__":
    n = write_values_tex(Path(sys.argv[1]) if len(sys.argv) > 1 else Path("../paper/tables"))
    print(f"values.tex: {n} macros")
